[project]
name = "pa4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipython>=8.28.0",
    "pytest>=8.3.3",
    "rich>=13.9.2",
    "ruff>=0.6.9",
]
